MUSIC_FOLDER: "/path/to/music"

PLAYLIST_SOURCE_FOLDER: "/path/to/source/playlists"
PLAYLIST_PUBLISHED_FOLDER: "/path/to/mpd/playlists"
DYNAMIC_PLAYLIST_FILE: "dynamic"
DEFAULT_PLAYLIST_FILE: "random"

OPENAI_API_KEY: "your-key"
OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
OPENAI_MODEL: "your-favorite-model"

DATABASE_UN: "dbuser"
DATABASE_PWD: "dbpass"
DATABASE_HOST: "dburl"
DATABASE_NAME: "dbname"

ES_URL: "http://ip_of_elasticsearch:9200"
ES_INDEX: "apollo"

SKIP_STRENGTH: 1
VOTE_STRENGTH: 5
RATING_THRESHOLD: 45

SUPPORTED_EXTENSIONS: [".mp3", ".flac", ".ogg", ".m4a", ".mp4"]

BITRATE_MULTIPLIERS:
  ".mp3": 1.0
  ".ogg": 1.3
  ".m4a": 1.2
  ".aac": 1.2
  ".mp4": 1.2
  ".flac": 1.0